[package]
name = "black_hole"
version = "0.1.0"
authors = ["Xelf-Laptop <xelfxendr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21.0"
image = "0.23.3"
num_cpus = "1.13.0"
